version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile  # Вказуємо шлях до Dockerfile для API
    ports:
      - "8080:8080" # Проксі для порту API
    networks:
      - ordersystem-network
    environment:
      - DefaultConnection=Host=ordersystem-db;Port=5432;Database=OrderSystem;Username=postgres;Password=1234

  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile  # Вказуємо шлях до Dockerfile для фронтенду
    ports:
      - "80:80" # Проксі для порту фронтенду
    networks:
      - ordersystem-network

networks:
  ordersystem-network:
    driver: bridge
